### ISSUE TITLE
Merge Chromium Processes as one with sublist

### ISSUE THREAD

**Issue by c-thun** [KrispyCamel4u/SysMonTask#66]
As everyone who used Chromium would be aware, it spawns tons of processes that each seem to take a low amount of memory but overall take a large amount of memory. Is there any way to merge Chromium processes into one?

**Comment by KrispyCamel4u** [comment]
Hi, thanks.
It would be great if you can share any screenshot to help me to get a very clear understanding?

**Comment by RDKRACZ** [comment]
This is the case with any Chromium-based browser.
Not sure what OP wants because if I understand correctly this is implemented - processes are in the tree view.

![Screenshot from 2021-06-24 12-49-27](https://user-images.githubusercontent.com/43277609/123250789-c48ddf80-d4ea-11eb-873a-6df6dbad61dd.png)

**Comment by c-thun** [comment]
I must have missed it. So sorry. Let me close the issue
